id: I37A15305
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W2PD19078
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2023-12-16T17:13:34.550444'
last_modified: '2023-02-01T00:00:00+00:00'
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19078
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19078
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྙིང་ཐིག་ཡ་བཞི།
  languages:
  - bo
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics: null
quality: null
bases:
  I2PD19082:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19082
      total_pages: 570
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I2PD19082.txt
    order: 1
  I2PD19084:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19084
      total_pages: 624
      volume_number: 3
      volume_pages_bdrc_intro: 2
    base_file: I2PD19084.txt
    order: 2
  I2PD19085:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19085
      total_pages: 544
      volume_number: 4
      volume_pages_bdrc_intro: 2
    base_file: I2PD19085.txt
    order: 3
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
  info_url: null
license: CC0
